resources:
    - name: build
      type: CronTrigger
      configuration:
        interval: '*/10 * * * *'
    - name: scanResult
      type: PropertyBag
      configuration:
          result: ''

pipelines:
    - name: Testing_Xray_2
      configuration:
          jfrogCliVersion: 2
      steps: 
        - name: test
          type: Bash
          configuration:
            integrations:
                - name: jfrogPat
            inputResources:
                - name: build
                  trigger: true
          execution:
            onStart:
                - add_run_variables result='false'
                # - write_output scanResult "result=$INITIALISER"
            onExecute:
                - touch test.txt
                - echo "Hello World" > test.txt
                - jfrog scan test.txt
            onSuccess:
                - add_run_variables result='true'
        - name: test_result
          type: Bash
          configuration:
              inputSteps:
                  - name: test
          execution:
              onExecute:
                  - |
                      if {{eq $result 'true'}} ; then
                          exit 0;
                      fi
                  - exit 1;
